# Generated by Django 3.0.8 on 2020-08-02 06:23

import ReceiptsExpenses.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ReceiptsExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveproducts',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер продукта'),
        ),
        migrations.AlterField(
            model_name='spentproducts',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер продукта'),
        ),
        migrations.AlterField(
            model_name='spentproducts',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(ReceiptsExpenses.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
