# Generated by Django 3.0.8 on 2020-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Бренд продукта')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды продуктов',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы продуктов',
            },
        ),
    ]
