# Generated by Django 3.0.8 on 2020-08-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Бренд продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='volume_rp',
            field=models.FloatField(blank=True, null=True, verbose_name='Получили'),
        ),
        migrations.AlterField(
            model_name='products',
            name='volume_sp',
            field=models.FloatField(blank=True, null=True, verbose_name='Потратили'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тип продукта'),
        ),
    ]
